# Generated by Django 6.0.5 on 2026-05-14 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True)),
                ('repair_description', models.TextField(blank=True)),
                ('ai_category', models.CharField(blank=True, max_length=120)),
                ('ai_damage_type', models.CharField(blank=True, max_length=120)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_suggested_responsibility', models.CharField(blank=True, choices=[('owner', 'Właściciel'), ('tenant', 'Najemca'), ('unresolved', 'Nierozstrzygnięte')], max_length=16)),
                ('ai_suggested_repair', models.TextField(blank=True)),
                ('ai_suggested_labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ai_suggested_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('responsibility', models.CharField(choices=[('owner', 'Właściciel'), ('tenant', 'Najemca'), ('unresolved', 'Nierozstrzygnięte')], default='unresolved', max_length=16)),
                ('cost_labor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_materials', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_currency', models.CharField(default='PLN', max_length=8)),
                ('mail_should_generate', models.BooleanField(default=False)),
                ('mail_template', models.CharField(blank=True, choices=[('owner_repair_notice', 'Powiadomienie o naprawie (właściciel)'), ('issue_verification_request', 'Prośba o weryfikację usterki')], max_length=40)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=120)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.case')),
            ],
            options={
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
