# Generated by Django 6.0.5 on 2026-05-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_element', models.CharField(max_length=120)),
                ('damage_cause', models.CharField(max_length=120)),
                ('damage_description', models.TextField()),
                ('repair_steps', models.TextField()),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_currency', models.CharField(default='PLN', max_length=8)),
                ('responsibility', models.CharField(blank=True, max_length=16)),
                ('coordinator_note', models.TextField(blank=True)),
                ('source_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_entries', to='api.case')),
            ],
            options={
                'verbose_name_plural': 'Knowledge base entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
